# Generated by Django 3.2.5 on 2021-07-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
